#!/usr/bin/env node

import * as fs from "fs";
import * as path from "path";
import { glob } from "glob";

interface TranslationEntry {
  [key: string]: string | TranslationEntry;
}

function getNestedValue(obj: TranslationEntry, path: string): string {
  const keys = path.split(".");
  let result: string | TranslationEntry = obj;
  for (const key of keys) {
    if (result && typeof result === "object" && key in result) {
      result = result[key];
    } else {
      return "string";
    }
  }
  return typeof result === "string" ? "string" : "string";
}

function generateTypeScript(
  translations: TranslationEntry,
  prefix: string = "",
  indent: string = "  "
): string {
  const lines: string[] = [];

  for (const [key, value] of Object.entries(translations)) {
    const currentKey = prefix ? `${prefix}.${key}` : key;

    if (typeof value === "string") {
      lines.push(`${indent}"${key}": string;`);
    } else if (value && typeof value === "object") {
      lines.push(`${indent}"${key}": {`);
      lines.push(generateTypeScript(value as TranslationEntry, currentKey, indent + "  "));
      lines.push(`${indent}}`);
    }
  }

  return lines.join("\n");
}

function generateInterface(
  translations: TranslationEntry,
  interfaceName: string = "Translations"
): string {
  return `// Auto-generated by react-native-text-kit
// Run: npx react-native-text-kit types

export interface ${interfaceName} {
${generateTypeScript(translations, "", "  ")}
}
`;
}

async function generateTypes(
  inputPattern: string,
  outputPath: string,
  interfaceName: string
): Promise<void> {
  const files = await glob(inputPattern);

  if (files.length === 0) {
    console.error(`No translation files found matching: ${inputPattern}`);
    process.exit(1);
  }

  let mergedTranslations: TranslationEntry = {};

  for (const file of files) {
    try {
      const content = fs.readFileSync(file, "utf-8");
      const translations = JSON.parse(content);
      mergedTranslations = { ...mergedTranslations, ...translations };
    } catch (error) {
      console.warn(`Warning: Could not parse ${file}:`, (error as Error).message);
    }
  }

  const typeScript = generateInterface(mergedTranslations, interfaceName);

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, typeScript);

  console.log(`✅ Generated TypeScript types at: ${outputPath}`);
  console.log(`   Processed ${files.length} translation file(s)`);
}

const args = process.argv.slice(2);

if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
  console.log(`
react-native-text-kit types

Generate TypeScript types from translation JSON files.

Usage:
  npx react-native-text-kit types --src <pattern> --output <path> [--interface <name>]

Options:
  --src, -s        Glob pattern for translation files (e.g., "./locales/*.json")
  --output, -o    Output path for TypeScript file (e.g., "./src/types/translations.ts")
  --interface     Interface name (default: "Translations")
  --help, -h      Show this help message

Example:
  npx react-native-text-kit types --src "./locales/*.json" --output "./src/types/translations.ts"
`);
  process.exit(0);
}

const srcArg = args.findIndex((a) => a === "--src" || a === "-s");
const outputArg = args.findIndex((a) => a === "--output" || a === "-o");
const interfaceArg = args.findIndex((a) => a === "--interface");

if (srcArg === -1 || outputArg === -1) {
  console.error("Error: Both --src and --output are required");
  process.exit(1);
}

const inputPattern = args[srcArg + 1];
const outputPath = args[outputArg + 1];
const interfaceName = interfaceArg !== -1 ? args[interfaceArg + 1] : "Translations";

generateTypes(inputPattern, outputPath, interfaceName);